Writable:
  LogLevel: "INFO"
  InsecureSecrets:
      DB:
        SecretName: "redisdb"
        SecretData:
          username: ""
          password: ""
  Pipeline:
    ExecutionOrder: "SetResponseData"

    Functions:
      SetResponseData:
        Parameters:
          ResponseContentType: ""
      FilterByProfileName:
        Parameters:
          ProfileNames: ""
          FilterOut: "false"
      FilterByDeviceName:
        Parameters:
          DeviceNames: ""
          FilterOut: "false"
      FilterBySourceName:
        Parameters:
          SourceNames: ""
          FilterOut: "false"
      FilterByResourceName:
        Parameters:
          ResourceNames: ""
          FilterOut: "false"

Service:
  Host: "192.168.1.100"
  Port: 59701
  StartupMsg: "app-rules-engine has Started"
  HealthCheckInterval: "10s"
  ServerBindAddr: "" # Leave blank so default to Host value unless different value is needed.
  MaxResultCount: 1024
  MaxRequestSize: 0 # Not currently used. Defines the maximum size of http request body in bytes
  RequestTimeout: "5s"
  EnableNameFieldEscape: false # The name field escape could allow the system to use special or Chinese characters in the different name fields, including device, profile, and so on.  If the EnableNameFieldEscape is false, some special characters might cause system error.  TODO: This is set to false by default to avoid breaking change and will be removed in EdgeX 4.0
  CORSConfiguration:
    EnableCORS: false
    CORSAllowCredentials: false
    CORSAllowedOrigin: "https://192.168.1.100"
    CORSAllowedMethods: "GET, POST, PUT, PATCH, DELETE"
    CORSAllowedHeaders: "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
    CORSExposeHeaders: "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
    CORSMaxAge: 3600


MessageBus:
  Protocol: "redis"
  Host: "192.168.1.100"
  Port: 6379
  Type: "redis"
  AuthMode: "usernamepassword"  # required for redis MessageBus (secure or insecure).
  SecretName: "redisdb"
  BaseTopicPrefix: "edgex" # prepended to all topics as "edgex/<additional topic levels>
  Optional:
    # Default MQTT Specific options that need to be here to enable environment variable overrides of them
    Qos:  "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive: "10" # Seconds (must be 2 or greater)
    Retained: "false"
    AutoReconnect: "true"
    ConnectTimeout: "5" # Seconds
    SkipCertVerify: "false"
    # Additional Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format: "nats"
    RetryOnFailedConnect: "true"
    QueueGroup: ""
    Durable: ""
    AutoProvision: "true"
    Deliver: "new"
    DefaultPubRetryAttempts: "2"
    Subject: "edgex/#" # Required for NATS JetStream only for stream auto-provisioning
    ClientId: "app-rules-engine"

Clients:
    core-metadata:
      Protocol: "http"
      Host: "192.168.1.100"
      Port: 59881

Trigger:
  Type: "edgex-messagebus"
  SubscribeTopics: "events/#" # Base topic is prepended to this topic when using edgex-messagebus
  # Note that the MessageBus connection above is used by edgex-messagebus trigger which is the default set in common config
  # Default value for SubscribeTopics is aslo set in common config
  PublishTopic: "rules-events"  # Base topic is prepened to this topic when using edgex-messagebus
